title: StekRadar
description: Reviews honestos de restaurantes e receitas testadas. Por Garapa.
url: "https://diegosouzafotografo-estrela.github.io"
baseurl: "/stekradar"
markdown: kramdown
theme: minima
future: true
permalink: /:title/
plugins:
  - jekyll-sitemap
